pipeline:
  name: fail-pipeline

stages:
  - name: build
    jobs:
      - name: build-echo
        steps:
          - run: echo "Build step"

  - name: test
    jobs:
      - name: test-fail
        steps:
          - run: exit 1
