pipeline:
  name: fail-pipeline

stages:
  - build
  - test

build_job:
  - stage: build
  - image: ubuntu:latest
  - script:
      - echo "Build step"

test_job:
  - stage: test
  - image: ubuntu:latest
  - script:
      - echo "About to fail"
      - exit 1
