pipeline:
  name: success-pipeline

stages:
  - build
  - test

build_job:
  - stage: build
  - image: ubuntu:latest
  - script:
      - echo "Build successful"

test_job:
  - stage: test
  - image: ubuntu:latest
  - script:
      - echo "Tests passed"
